lib/io_rails_app/base/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_scope :user do 
    get "/users" => "users#index" 
    get "/users/:username" => 'users#show'
  end

  namespace :admin do
    root "base#index"
    resources :users
  end

  if ::Rails.env.production? 
    match '*path', via: :all, to: 'home#error_404'
  end
end

lib/io_rails_app/base/app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set

  # scope :read_root, -> { where(:name => 'read').first }

end

lib/io_rails_app/base/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!

  layout 'default'
  
  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @count = User.users_count 
  end
end

lib/io_rails_app/base/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_filter :pre_load

  def pre_load
    @user = User.find(params[:id]) if params[:id]
  end

  before_action :pre_load, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]

  def user_params
    params.require(:user).permit(:username, :email, :avatar, :password, :nation, :residence, :created_at, :updated_at)
  end
  

  def index
    @users = User.search_and_order(params[:search])
  end
  
  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to "/admin/users"
    end
  end


  def update
    if @user.update_attributes(user_params)
      redirect_to "/admin/users"
    end
  end


  def destroy
    if @user.destroy
      redirect_to "/admin/users"
    end
  end
  
end

lib/io_rails_app/base/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'default' 


  before_action :configure_permitted_parameters, if: :devise_controller?

  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username]
    devise_parameter_sanitizer.for(:account_update) << [:username]
  end


  def render_404
    render_optional_error_file(404)
  end

  def render_403
    render_optional_error_file(403)
  end

  def render_optional_error_file(code)
    render file: "#{Rails.root}/public/#{code}.html", status: code, layout: true
  end

  
  io_require_admin


end

lib/io_rails_app/base/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end


  def admin
  end


  def error_404
    render_404
  end



end

lib/io_rails_app/base/app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  before_filter :find_user, only: [:show]

  def user_params
    params.require(:user).permit(:avatar)
  end

  def index
  end

  def show
    # @user = current_user
  end


  protected
    def find_user
      @user = User.where("lower(username) = ?", params[:username].downcase).first

      render_404 if @user.nil?
    end


  

  
end

lib/io_rails_app/base/app/helpers/application_helper.rb
module ApplicationHelper

  def show_nav_active(controller, action)
    'active' if params[:action] == action && params[:controller] == controller
  end

end

lib/io_rails_app/base/app/views/admin/base/index.html.erb
<h1>Admin <small>Home</small></h1>
<div class="row">
  <div class="col-sm-4">
    <h3>Menu</h3>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= "#{pluralize(@count, 'user')}" %></small></h4>
    <hr/>
  </div>
  
  <div class="col-sm-4">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>
  
  <div class="col-sm-4">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>
  
</div>

lib/io_rails_app/base/app/views/admin/users/_menu.html.erb
<ul class="nav nav-tabs mb-20" role="tablist">
    <li <% if current_page?(:action => 'index') %> class="active" <% end %>>
      <%= link_to "User List", "/admin/users", :method => :get %>
    </li>
    <li<% if current_page?(:action => 'new') %> class="active" <% end %>>
      <%= link_to "New User", '/admin/users/new', :method => :get %>
    </li>
</ul>

lib/io_rails_app/base/app/views/admin/users/edit.html.erb
<%= render '/admin/users/menu' %>


<div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">


        <div class="panel-body">


<%= simple_form_for @user, :url => "/admin/users/#{@user.id}" do |f| %>
          

            <p>
              <label>Username</label>
            </p>
            <p><%= f.text_field :username, :required => true, :class => "width-input", autocomplete: "off" %></p>

            <p><label>Email</label></p>
            <p><%= f.email_field :email, :required => true, :class => "width-input", autofocus: true %></p>

            <p><label>Password</label></p>
            <p> <%= f.password_field :password, :required => true, :class => "width-input", autocomplete: "off" %></p>
          

          <p style="margin-top: 30px;"><%= f.submit "Save" %></p>
        <% end %>



     </div>



    </div>

  </div>
</div>

lib/io_rails_app/base/app/views/admin/users/index.html.erb
<%= render '/admin/users/menu' %>
 

<div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">


        <div class="panel-body">
          <%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
            <p>
              <%= text_field_tag :search, params[:search] %>
              <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
              <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
            </p>
          <% end %>

          <table class="table">
            <tr class="table-caption">
              <th>Username</th>
              <th>Email</th>
              <th>Created</th>
              <th>Updated</th>
              <th></th>
              <th></th>
            </th>
            <% @users.each do |u| %>
                  <tr>
                    <td class="table-normal"><%= u.username %></td>
                    <td class="table-normal"><%= u.email %></td>
                    <td class="table-normal"><%= time_ago_in_words u.created_at %></td>
                    <td class="table-normal"><%= time_ago_in_words u.updated_at %></td>
                    <td class="table-normal"><%= link_to "edit", "/admin/users/#{u.id}/edit" %></td>
                    <td class="table-normal"><%= link_to "delete", "/admin/users/#{u.id}", :method => :delete, data: { confirm: "Delete?"} %></td>
                  </tr>
                  <% end %>
          </table>


          <%= paginate @users %>

     </div>



    </div>

  </div>
</div>

lib/io_rails_app/base/app/views/admin/users/new.html.erb
<%= render '/admin/users/menu' %>



<div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">


        <div class="panel-body">


<%= simple_form_for @user, :url => "/admin/users" do |f| %>
          

            <p>
              <label>Username</label>
            </p>
            <p><%= f.text_field :username, :required => true, :class => "width-input", autocomplete: "off" %></p>

            <p><label>Email</label></p>
            <p><%= f.email_field :email, :required => true, :class => "width-input", autofocus: true %></p>

            <p><label>Password</label></p>
            <p> <%= f.password_field :password, :required => true, :class => "width-input", autocomplete: "off" %></p>


          <p style="margin-top: 30px;"><%= f.submit "Save" %></p>
        <% end %>



     </div>



    </div>

  </div>
</div>

lib/io_rails_app/base/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>

<div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="flash-msg alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>


      </div>
  </div>
</div>

lib/io_rails_app/base/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oncedoce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

lib/io_rails_app/base/app/views/layouts/default.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="<%= @keywords if @keywords %>" />
    <meta name="title" content="<%= @title if @title %>" />

    <title>YourApp <%= ' - ' + @title if @title %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'custom_as_default', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>



<body>

  <div class="wrapper">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button aria-controls="navbar" aria-expanded="true" data-target="#navbar" data-toggle="collapse" class="navbar-toggle" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/admin" class="navbar-brand">YourApp</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar" aria-expanded="true" style="">
          <ul class="nav navbar-nav">
            <li>
                <a href="/admin/">系统任务</a>
            </li>

          </ul>


          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li>
                <a href="/users/<%= current_user.username %>" title="">
                    <%= current_user.username %>
                </a>
            </li>
            <li>
                <%= link_to t('logout'), '/users/sign_out', :method => :delete %>
            </li>
            <% else %>
              <li>
                <a href="/users/sign_in" title="<%= t('login') %>"><%= t('login') %></a>
              </li>
              <li>
                <a href="/users/sign_up" title="<%= t('register') %>"><%= t('register') %></a>
              </li>
            <% end %>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>




    <%= render 'layouts/messages' %>



    <!-- Page Content -->
    <div class="container" style="min-height: 360px; margin-bottom: 20px;">

        <%= yield %>

    </div>
    <!-- /.container -->


    <div class="container">
        <!-- Footer -->
        <footer>
            <div class="row well">
                <div class="col-lg-12">
                    <p>
                      <span>Copyright &copy; 2014</span>
                      <span class="pull-right">
                        <a href="" class="mr-10"></a>
                        <a href=""></a>
                      </span>
                    </p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->


  </div>


</body>
</html>

lib/io_rails_app/base/app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="<%= @keywords if @keywords %>" />
    <meta name="title" content="<%= @title if @title %>" />

    <title>YourApp <%= ' - ' + @title if @title %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'custom_as_simple', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>



<body>

  <div class="wrapper">

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">YourApp</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
                <a href="/">Home</a>
            </li>

          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to t('logout'), '/users/sign_out', :method => :delete %></li>
              </ul>
            </li>

            <% else %>
              <li>
                <a href="/users/sign_in" title="<%= t('login') %>"><%= t('login') %></a>
              </li>
              <li>
                <a href="/users/sign_up" title="<%= t('register') %>"><%= t('register') %></a>
              </li>
            <% end %>

            <!-- <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li> -->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>




    <%= render 'layouts/messages' %>



    <!-- Page Content -->
    <div class="container-fluid" style="min-height: 360px; margin-bottom: 20px;">

        <%= yield %>

    </div>
    <!-- /.container -->


    <div class="container-fluid">
        <!-- Footer -->
        <footer>
            <div class="row well">
                <div class="col-lg-12">
                    <p>
                      <span>Copyright &copy; 2014</span>
                      <span class="pull-right">
                        <a href="" class="mr-10"></a>
                        <a href=""></a>
                      </span>
                    </p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->


  </div>



  
</body>
</html>

lib/io_rails_app/base/app/views/users/show.html.erb
<div class="panel panel-default">

    <div class="panel-heading"><strong></strong></div>

    <div class="panel-body">



    </div>




</div>